config/routes.rb
Oo::Application.routes.draw do

 resources :computers, :as => "sounds",:controller => "sounds" do
    resources :lists ,:controller => "albums"
 end
  resources :images,:as => "studionames" do
    resources :nums ,:as => "studios"
 end
 resources :hekoms
 resources :sessions, only: [:new, :create, :destroy]
resources :users do
  
    resources :microposts do
       get 'admin', :on => :collection
    end

end
  root to: 'pages#index'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'
  match '/signup', to: 'users#new'
   match '/aboutus', to: 'pages#aboutus'
   
   match '/services/9', to: 'pages#three3'
   match '/services/8', to: 'pages#three2'
  match '/services/7', to: 'pages#three1'
   match '/services/6', to: 'pages#two2'
   match '/services/5', to: 'pages#two1'
   match '/services/4', to: 'pages#one4'
   match '/services/3', to: 'pages#one3'
   match '/services/2', to: 'pages#one2'
   match '/services/1', to: 'pages#one1'
   match '/services', to: 'pages#services'
   
  match '*a', :to => 'pages#index'
  

end

app/models/hekom.rb
class Hekom < ActiveRecord::Base
     attr_accessible :name
end

app/controllers/hekoms_controller.rb
class HekomsController < ApplicationController
    before_filter :signed_in_user, only: [:new, :edit, :update,:destroy]
  before_filter :admin_check, only: [:new, :edit, :update,:destroy]

     def destroy
 Hekom.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to sounds_path
  end
  def index
        @sound = Hekom.paginate(:page => params[:page],:per_page => 3)
  end
def edit
    @sound = Hekom.find(params[:id])
  
  end
  
    def update
    @sound = Hekom.find(params[:id])
    if @sound.update_attributes(params[:hekom])
    flash[:success] = "Profile updated"
      redirect_to @sound 
    else
      render 'edit'
    end
  end
  
  def show

  end
   def create
    @sound = Hekom.new(params[:hekom]) 
    if @sound.save
            flash[:success] = "Welcome to the Sample App!"
      redirect_to @sound
    else
      render 'new'
    end
  end
  
  def new
    @sound = Hekom.new
  
  end
    private

    def signed_in_user
      redirect_to  signin_path, notice: "Please sign in." unless signed_in?
    end
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user) || admin_check?
    end
    def admin_check
      redirect_to(root_path) unless  admin_check?
    end
end

app/views/hekoms/edit.html.erb
<table class="profile">
  <tr>
   
    <td class="sidebar1 round">
     <strong>  </strong>
     
    </td>
  </tr>
</table><br /><br />
<center>
<%= form_for  @sound,:html => { :multipart => true } do |f| %>
  <div class="field">
    <%= f.label :name, "اسم الشريط" %><br />
    <%= f.text_field :name %>
  </div>

  
 
  <div class="actions">
    <%= f.submit "اضـافة" %>
  </div>
  <br />  <br />
<% end %>

<% if @sound.errors.any? %>
  <div id="error_explanation">
    
    <b>تاكد اخي العزيز من الاخطاء التالية</b>
    <ul>
   
      <li> فارغ، يرجى ملء احد الحقول -</li>
 
    </ul>
  </div>
<% end %>

app/views/hekoms/index.html.erb
<table class="profile">
  <tr>
   
    <td class="sidebar1 round">
     <strong>    <%= link_to "اضافة شريط",new_hekom_path%>
</strong>
     
    </td>
  </tr>
</table><br /><br />

<table class="profile" summary="Profile information">
  <tr>
    <td class="main">
                
        <table class="microposts" summary="User microposts">         	  <% @sound.each do |sound| %>

        	<tr>
  <td class="micropost">
<span class="content"><h5><%= link_to sound.name, sound %></h5></span> 


 <span class="timestamp">
      Posted <%= time_ago_in_words(sound.created_at) %> ago.||<%= sound.created_at %>
    </span>
 <span class="content">  
 	      <% if signed_in? %>

 	<% if admin_check? %>
    | <%= link_to "delete", sound , method: :delete, 
                                  confirm: "You sure?" %>
                                  <% if admin_check?  %>
                                    | <%= link_to "Edit", edit_studioname_path(sound), 
                                  confirm: "You sure?" %>
  <% end %> <% end %>
  <% end %></span> 
  </td>
   
    	<td class="gravatar">
    		
   		<br />
  </td><% end %>
  </tr> 
  
        </table>                <%= will_paginate @sound %>

    </td>
  
</table>

app/views/hekoms/new.html.erb
<table class="profile">
  <tr>
   
    <td class="sidebar1 round">
     <strong>  </strong>
     
    </td>
  </tr>
</table><br /><br />
<center>
<%= form_for  @sound do |f| %>
  <div class="field">
    <%= f.label :name, "اسم الشريط" %><br />
    <%= f.text_field :name %>
  </div>

  
  
  </div>
  
  <div class="actions">
    <%= f.submit "اضـافة" %>
  </div>
  <br />  <br />
<% end %>

<% if @sound.errors.any? %>
  <div id="error_explanation">
    
    <b>تاكد اخي العزيز من الاخطاء التالية</b>
    <ul>
   
      <li> فارغ، يرجى ملء احد الحقول -</li>
 
    </ul>
  </div>
<% end %>

app/views/hekoms/show.html.erb
 
 <% flash.each do |key, value| %>
          <div class="flash <%= key %>"><p class="o1">أهلاً بك اخي العزيز تمت العملية  بنجاح</p> </div>
        <% end %>
        <center>

  <table class="front" summary="For signed-in users">
    <tr>
      <td class="main">
         </td>
 
    </tr>
  </table>
        <table class="profile">
  <tr>
    <td class="main"> <% if signed_in? %><% if admin_check? %>
  <%= link_to "اضافة صوت",new_studioname_studio_path(@sound)%><% end %> <% end %>
    
    </td>
    <td class="sidebar round" style="width: 140%;">
      <%= @sound.name %><strong> : الاسم</strong> <br />
  
    </td>
      	
  </tr>
</table>
<br />
<br />
<br />

<table class="profile" summary="Profile information">
  <tr>
    <td class="main">
                
        <table class="microposts" summary="User microposts">  <% @sound1.each do |sound| %>

        	<tr>
       
   
  <td class="micropost">
<span class="content"><h5><%= sound.name %></h5></span> 
    	
    	<br />
<span class="content">   <% if signed_in? %><% if admin_check? %>
    | <%= link_to "delete", [@sound,sound], method: :delete, 
                                  confirm: "You sure?" %>
                                  <% if admin_check?  %>
                                    | <%= link_to "Edit", edit_sound_list_path(@sound,sound), 
                                  confirm: "You sure?" %>
  <% end %> <% end %>
  <% end %></span> 
  </td>
  </td><% end %>
  </tr> 
   <%= will_paginate @sound1 %>
        </table>               
    </td>
  </tr>
 </table>