config/routes.rb
Oo::Application.routes.draw do

 resources :computers, :as => "sounds",:controller => "sounds" do
    resources :lists ,:controller => "albums"
 end
  resources :images,:as => "studionames" do
    resources :nums ,:as => "studios"
 end
 resources :hekoms
 resources :sessions, only: [:new, :create, :destroy]
resources :users do
  
    resources :microposts do
       get 'admin', :on => :collection
    end

end
  root to: 'pages#index'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'
  match '/signup', to: 'users#new'
   match '/aboutus', to: 'pages#aboutus'
   
   match '/services/9', to: 'pages#three3'
   match '/services/8', to: 'pages#three2'
  match '/services/7', to: 'pages#three1'
   match '/services/6', to: 'pages#two2'
   match '/services/5', to: 'pages#two1'
   match '/services/4', to: 'pages#one4'
   match '/services/3', to: 'pages#one3'
   match '/services/2', to: 'pages#one2'
   match '/services/1', to: 'pages#one1'
   match '/services', to: 'pages#services'
   
  match '*a', :to => 'pages#index'
  

end

app/models/sound.rb
class Sound < ActiveRecord::Base
  has_many :asets
   has_many :lists
  attr_accessible :content , :name,:asets_attributes
  accepts_nested_attributes_for :asets , :allow_destroy=>true
  
   validates :name, presence: true, length: { maximum: 50 }
    validates :content, presence: true, length: { maximum: 50 }
end

app/controllers/sounds_controller.rb
class SoundsController < ApplicationController
    before_filter :signed_in_user, only: [:new, :edit, :update,:destroy]
  before_filter :admin_check, only: [:new, :edit, :update,:destroy]
  
     def destroy
 Sound.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to sounds_path
params[:id]  end
  def index
        @sound = Sound.paginate(:page => params[:page],:per_page => 5)
  end
def edit
   @sound = Sound.find(params[:id])
   @sound.asets.build
  end
  
    def update
    @sound = Sound.find(params[:id])
    if @sound.update_attributes(params[:sound])
    flash[:success] = "Profile updated"
      redirect_to @sound 
    else
      render 'edit'
    end
  end
 
  def show


      if Sound.exists?(params[:id]) 
     @sound = Sound.find(params[:id])
           @sound1=@sound.lists.paginate(:page => params[:page],:per_page => 1)

    else
      redirect_to root_path
    
end
  end
   def create
    @sound = Sound.new(params[:sound]) 
    if @sound.save

            flash[:success] = "Welcome to the Sample App!"
      redirect_to @sound
    else
      render 'new'
    end
  end
  
  def new
    @sound = Sound.new
    @sound.asets.build
  end
    private
 def nonnegative_float?
    !!match(/\A\+?\d+(?:\.\d+)?\Z/)
  end
    def signed_in_user
      redirect_to  signin_path, notice: "Please sign in." unless signed_in?
    end
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user) || admin_check?
    end
    def admin_check
      redirect_to(root_path) unless  admin_check?
    end
end

app/helpers/sound_helper.rb
module SoundHelper

end

app/views/sounds/edit.html.erb
<table class="profile">
  <tr>
   
    <td class="sidebar1 round">
     <strong>  </strong>
     
    </td>
  </tr>
</table><br /><br />
<center>
<%= form_for  @sound,:html => { :multipart => true } do |f| %>
  <div class="field">
    <%= f.label :name, "اسم الشريط" %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content, "وصف الشريط" %><br />
    <%= f.text_area :content %>
  </div>
  <%= f.fields_for :asets do |aset_fields|%>
  <div class="field">
  	 <% if aset_fields.object.new_record?%>
  <%= aset_fields.file_field :image%>
  <% end %>
    <% end %>
  </div>
    <%= f.fields_for :asets do |a|%>
      <% unless a.object.new_record?%>

  <div class="field">
<%= link_to image_tag(a.object.image.path(:thumb)),a.object.image.path(:small)%>
<%= a.check_box :_destroy%>


  
  </div>
    <% end %> <% end %>
  <div class="actions">
    <%= f.submit "اضـافة" %>
  </div>
  <br />  <br />
<% end %>

<% if @sound.errors.any? %>
  <div id="error_explanation">
    
    <b>تاكد اخي العزيز من الاخطاء التالية</b>
    <ul>
   
      <li> فارغ، يرجى ملء احد الحقول -</li>
 
    </ul>
  </div>
<% end %>

app/views/sounds/index.html.erb
	<div class="">
<center>
   <div class="holder_content1">
		<section>

	</section>
	

		</div>
		
   <div class="holder_content">
 
       <section class="group7">
       	<h3>اخر العروض للاجهزة</h3>
       	<br />
 <% if signed_in? %>
    <% if admin_check? %>
   <table class="profile1">
  <tr>
   
    <td class=" round" >
     <strong>    <%= link_to "اضافة لابتوب",new_sound_path%>
</strong>
     
    </td>
  </tr>
</table>
<% end %>

<% end %>
<table class="o" summary="Profile information">
  <tr>
    <td >
                 <%= will_paginate @sound ,:class=>"apple_pagination",:previous_label=>"",:next_label=>""%>

        <table class="microposts" summary="User microposts" style="text-align: center;width: 460px; color:#A9E7FF">  <% @sound.each do |sound| %>

        	<tr>
  <td class="micropost"style="text-align: right;font-size: 12px;width: 450px;" class="microposts">
<span class="content"><p class="microposts"style="text-align: center;"><%= link_to sound.name, sound %></p></span> 
<span class="content"><p style="text-align: right;font-size: 12px;" class="o"> <%=  sound.content %><></span> <br />

 <span class="timestamp">
 	
           	<p style="text-align: right;font-size: 12px;" class="o"> <span style="float: left;"><%= sound.created_at %></span> </p>

    </span>
 <span class="content">  
 	      <% if signed_in? %>

 	<% if admin_check? %>
    | <%= link_to "delete", sound , method: :delete, 
                                  confirm: "You sure?" %>
                                  <% if admin_check?  %>
                                    | <%= link_to "Edit", edit_sound_path(sound), 
                                  confirm: "You sure?" %>
  <% end %> <% end %>
  <% end %></span> 
  </td>
   
    	<td class="gravatar" style="opacity: 0.9;">
    		<% x= Sound.find(sound.id) %>
    			    		<%= link_to image_tag(x.asets.first.image.url(:thumb)),sound%>

   		<br />
  </td><% end %>
  </tr> 
        </table>              
    </td>
  
</table>

   	</section>  
   <section class="group6">
   	
   	  <%= image_tag("one1.png", :class=>"o")%>
  

	</section>

  
   </div>

   <!--end holder-->
</center>
<br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />

<br /><br /><br /><br /><br /><br /><br /><br /></p>
<br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />

app/views/sounds/new.html.erb
<table class="profile">
  <tr>
   
    <td class="sidebar1 round">
     <strong>  </strong>
     
    </td>
  </tr>
</table><br /><br />
<center>
<%= form_for  @sound,:html => { :multipart => true } do |f| %>
  <div class="field">
    <%= f.label :name, "اسم الشريط" %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content, "وصف الشريط" %><br />
    <%= f.text_area :content %>
  </div>
  <%= f.fields_for :asets do |aset_fields|%>
  <div class="field">
  <%= aset_fields.file_field :image%>
  <% end %>
  
  </div>
    <%= f.fields_for :asets do |a|%>
  <% unless a.object.new_record?%>
  <div class="field">
<%= link_to image_tag(a.object.image.url(:thumb)),a.object.image.url(:small)%>
 
  
  </div>
   <% end %>
  <% end %>
  <div class="actions">
    <%= f.submit "اضـافة" %>
  </div>
  <br />  <br />
<% end %>

<% if @sound.errors.any? %>
  <div id="error_explanation">
    
    <b>تاكد اخي العزيز من الاخطاء التالية</b>
    <ul>
   
      <li> فارغ، يرجى ملء احد الحقول -</li>
 
    </ul>
  </div>
<% end %>

app/views/sounds/show.html.erb
 <div id="best">
        <center>

   <div class="holder_content">
 
       <section class="group7">
  <table class="front" summary="For signed-in users">
    <tr>
      <td class="main">
         </td>
 
    <td class="main"> <% if signed_in? %><% if admin_check? %>
  <%= link_to "اضافة مواصفات",new_sound_list_path(@sound)%><% end %> <% end %>
    
    </td>
    </tr>
  </table>
        <table class="o"style="text-align: center;width: 430px; color:#A9E7FF">
  <tr>
    <td class="sidebar round">
      <%= @sound.name %> <br />
    </td>
    
  </tr>
</table>

<br />
  <table class="o"style="text-align: center;width: 430px; color:#A9E7FF;">
  	<center>
  		<h3>صور الجهاز</h3>
  <tr>	<td class="gravatar" style="text-align: center;width: 430px; color:#A9E7FF;margin:0px auto;">
    		<% for aset in  @sound.asets%>
    		<%= link_to image_tag(aset.image.url(:thumb)),aset.image.url%>
    		
    		<% end %>
   		<br />
  </td></tr></center>
</table>
<table class="profile" summary="Profile information">
  <tr>
  	  		<h3>مواصفات الجهاز</h3>

    <td class="main">
    	                 <%= will_paginate @sound1 , :class=>"apple_pagination" ,:previous_label=>"",:next_label=>""%>

        <table class="microposts" summary="User microposts"style="text-align: center;width: 430px; color:#A9E7FF;"> 
        	 <% @sound1.each do |sound| %>
        	<tr>
        		
  <td class="micropost">
<span class="content"><p><%= raw sound.name%></p></span> 
  <% if signed_in? %><% if admin_check? %>
<span class="content">   
    | <%= link_to "delete", [@sound,sound], method: :delete, 
                                  confirm: "You sure?" %>
                                  <% if admin_check?  %>
                                    | <%= link_to "Edit", edit_sound_list_path(@sound,sound), 
                                  confirm: "You sure?" %>
  <% end %> <% end %>
  <% end %></span> 
  </td>
  </td><% end %>
  </tr> 
        </table>               
    </td>
  </tr>    

 </table>
 <br />
   	<p style="text-align: right;"class="o">وفي حالة الاستفسارات او رغبتـكم يمكنكـم التسجيل والمتابعه  </p>

	<a href="" class="e"><%= link_to "ســجل معنــا بدخولـــك" ,signin_path ,:class=>"o"%></a>
</div>
 </section>  
   <section class="group6">
   	
   	  <%= image_tag("one1.png", :class=>"o")%>
 

<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
	</section>
	
	</div>