config/routes.rb
Oo::Application.routes.draw do

 resources :computers, :as => "sounds",:controller => "sounds" do
    resources :lists ,:controller => "albums"
 end
  resources :images,:as => "studionames" do
    resources :nums ,:as => "studios"
 end
 resources :hekoms
 resources :sessions, only: [:new, :create, :destroy]
resources :users do
  
    resources :microposts do
       get 'admin', :on => :collection
    end

end
  root to: 'pages#index'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'
  match '/signup', to: 'users#new'
   match '/aboutus', to: 'pages#aboutus'
   
   match '/services/9', to: 'pages#three3'
   match '/services/8', to: 'pages#three2'
  match '/services/7', to: 'pages#three1'
   match '/services/6', to: 'pages#two2'
   match '/services/5', to: 'pages#two1'
   match '/services/4', to: 'pages#one4'
   match '/services/3', to: 'pages#one3'
   match '/services/2', to: 'pages#one2'
   match '/services/1', to: 'pages#one1'
   match '/services', to: 'pages#services'
   
  match '*a', :to => 'pages#index'
  

end

app/models/adid.rb
class Adid < ActiveRecord::Base
  belongs_to :role
  belongs_to :user
  
end

app/models/aset.rb
class Aset < ActiveRecord::Base
  belongs_to :sound
  belongs_to :list
    attr_accessible :image
validates_attachment_content_type :music,
  :content_type => [ 'audio/mpeg', 'audio/x-mpeg', 'audio/mp3', 'audio/x-mp3', 'audio/mpeg3', 'audio/x-mpeg3', 'audio/mpg', 'audio/x-mpg', 'audio/x-mpegaudio' ]
   validates_attachment_size :music, :less_than => 10.megabytes                                    
  has_attached_file :image,     :url => '/assets/:id/:style.:extension',
                    :path => ':rails_root/app/assets/images/:id/:style.:extension',
    :styles => {
      :thumb=> "80x80#",
      :small  => "150x150>", 
 }
end

app/models/asett.rb
class Asett < ActiveRecord::Base
  belongs_to :list
  
  has_attached_file :music, 
    :url => '/assets/musics/:id/:style.:extension',
                    :path => ':rails_root/app/assets/audios/musics/:id/:style.:extension'
                
validates_attachment_presence :music
   validates :music, presence: true

  validates_attachment_content_type :music, :content_type => [ 'audio/mpeg', 'audio/x-mpeg', 'audio/mp3', 'audio/x-mp3', 'audio/mpeg3', 'audio/x-mpeg3', 'audio/mpg', 'audio/x-mpg', 'audio/x-mpegaudio' ],

                                    :message => 'file must be of filetype .mp3'

  validates_attachment_size :music, :less_than => 10.megabytes  
end

app/models/asset.rb
class Asset < ActiveRecord::Base
  belongs_to :product
end

app/models/feed.rb
class Feed < ActiveRecord::Base
  belongs_to :micropost 
  belongs_to :user 
end

app/models/hekom.rb
class Hekom < ActiveRecord::Base
     attr_accessible :name
end

app/models/list.rb
class List < ActiveRecord::Base
   has_many :asetts
   belongs_to :sounds
   attr_accessible  :name,:asetts_attributes
  accepts_nested_attributes_for :asetts , :allow_destroy=>true
     

   validates :name, presence: true, length: { maximum: 503333 }

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
   attr_accessible :content , :name
   has_many :feeds
 has_many :users , through: :feeds ,  :foreign_key => "user_id"
 
      validates :name, :presence => true, :length => { :maximum => 140 }
  default_scope order: 'microposts.created_at DESC'
 validates :content, :presence => true, :length => { :maximum => 1400 }
end

app/models/role.rb
class Role < ActiveRecord::Base
 has_many :adids
 has_many :users , through: :adids
end

app/models/shere.rb
class Shere < ActiveRecord::Base
  belongs_to :studio
     attr_accessible :image
  has_attached_file :image,:url => '/assets/img/:id/:style.:extension',
                    :path => ':rails_root/app/assets/images/img/:id/:style.:extension',
    :styles => {
      :thumb=> "80x80#",
      :small  => "150x150>", 
 }
end

app/models/sound.rb
class Sound < ActiveRecord::Base
  has_many :asets
   has_many :lists
  attr_accessible :content , :name,:asets_attributes
  accepts_nested_attributes_for :asets , :allow_destroy=>true
  
   validates :name, presence: true, length: { maximum: 50 }
    validates :content, presence: true, length: { maximum: 50 }
end

app/models/studio.rb
class Studio < ActiveRecord::Base
   has_many :sheres
   belongs_to :studionames
   attr_accessible  :name,:asetts_attributes,:subject
  accepts_nested_attributes_for :sheres , :allow_destroy=>true
     

   validates :name, presence: true, length: { maximum: 50 }
end

app/models/studioname.rb
class Studioname < ActiveRecord::Base
  attr_accessible :content , :name,:asets_attributes
     has_many :studio

   validates :name, presence: true, length: { maximum: 50 }
    validates :content, presence: true, length: { maximum: 50 }
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime        not null
#  updated_at :datetime        not null
#

class User < ActiveRecord::Base
    has_many :adids
   has_many :feeds
    has_many :microposts , through: :feeds,:dependent => :destroy
    has_many :roles , through: :adids
  attr_accessible :name, :email, :password, :password_confirmation
  has_secure_password
  before_save :create_remember_token

  validates :name, presence: true, length: { maximum: 50 }, uniqueness: { case_sensitive: false }
  
  valid_email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: valid_email_regex },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true ,:length       => { :within => 6..40 }
   # The following methods are needed to be minimally implemented
   def feedz
  microposts
end
 private
  
    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/helpers/album_helper.rb
module AlbumHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  
   def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    clear_return_to
  end
  def admin_check(user)
 a = Adid.find(user) || false
if a.role.name == "admin" 
  true || false
end
end
   def gravatar_for1(user, options = {})
   options = { :size => 4 }.merge(options)
 
    gravatar_url = user
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
   def gravatar_for(user, options = {})
   options = { :size => 4 }.merge(options)

    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
 
    gravatar_url = "http://www.gravatar.com/avatar/#{gravatar_id}?s=80"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
def admin_check?
  if Adid.exists?(current_user.id)

 a = Adid.find(current_user.id)
if a.role.name == "admin" 
  true 
end
else
  false
end
end

def admin_user
  @admin = admin_user(user)
end
def wrap(content)
    sanitize(raw(content.split.map{ |s| wrap_long_string(s) }.join(' ')))
  end

  

def admin_user(user)
    if Adid.exists?(current_user.id)

 a = Adid.find(current_user.id)
if a.role.name == "admin" 
  user = current_user.id
end
end
end
  def store_location
    session[:return_to] = request.fullpath
  end
 def sign_in(user)
  cookies.permanent[:remember_token] = user.remember_token
    current_user = user
  end
    def sign_out
    cookies.delete(:remember_token)
  end
    def signed_in?
    !current_user.nil?
  end
  def current_user=(user)
    @current_user = user
  end
  def current_user
    @current_user ||= user_from_remember_token
  end
  def current_user?(user)
    user == current_user
  end
  private
  
    def wrap_long_string(text, max_width = 30)
      zero_width_space = "&#8203;"
      regex = /.{1,#{max_width}}/
      (text.length < max_width) ? text : 
                                  text.scan(regex).join(zero_width_space)
    end
def clear_return_to
      session.delete(:return_to)
    end
    def user_from_remember_token
      remember_token = cookies[:remember_token]
      User.find_by_remember_token(remember_token) unless remember_token.nil?
    end
end

app/helpers/sound_helper.rb
module SoundHelper

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer ">
  
  <nav style="float: left;">
    <ul>
	<li><%= link_to "من نحن", 	aboutus_path %></li>
	<li><%= link_to "خدماتـنا", 	services_path %></li>
         <li><%= link_to "الرئيسية", 	root_path %></li>
    </ul>
  </nav><small style="float: right;">

   القائم لخدمــات الحاسوب
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner1">
    <div class="container">
      <nav>
        <ul class="nav pull-left">
   <li><%= link_to "للأستفــسار : 0097333782338", 	root_path %></li>
   </ul>
      </nav>
              <span class="nav pull-right">

      	
            <%= link_to "القــائم لخدمــات الحاسوب", '#', id: "logo" %>
</span>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>القائم لخدمات الحاسوب</title>
    <%= stylesheet_link_tag    "custom1", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>    
  </head>
  
  <body>
  	    
    <%= render 'layouts/header' %>
    <div id="back" class="container">
    	<header id="x" class="navbar" >
    <div class="container">
            <span class="nav pull-right">
<h3 id="logo1">القــائم</h3>
</span>	
      <nav>
        <ul class="nav pull-left  o">
         
           	<li><%= link_to "من نحن", 	aboutus_path %></li>
     
      <% if signed_in? %>
      
        <li><%= link_to "تسجيل الخروج", signout_path, method: :delete , confirm: "هل انت متأكـد ؟"%></li>
       <li><%= link_to "رسائلي ", user_microposts_path(current_user) if !admin_check?%></li>
        
      <% else %>
        <li><%= link_to "تسجيل الدخول", signin_path %></li>
      <% end %>
            <% if signed_in? %>

       <% if admin_check?   %>
  
	<li><%= link_to "الاعضـاء", 	users_path %></li>
	<li><%= link_to "رسـائل الاعضاء" , 	admin_user_microposts_path(current_user) %></li>
		<% end %>
		 <% end %>
	<li><%= link_to "عروض الاجهزة", 	sounds_path %></li>
	<li><%= link_to "خدماتـنا", 	services_path %></li>
         <li><%= link_to "الرئيسية", 	root_path %></li>
</ul>
      </nav>
              <span class="nav pull-right">

</span>
</header>

  <% flash.each do |key, value| %>
 <%if :error ==  key %>

        <div class="alert alert-<%= key %>" style="margin:0px auto ;text-align: center;opacity: 0.2; ">
      	 لم تتم المدخولات بلطريقة المستوجبة لدخول حاول مرة اخرى
<%end%>
<% if :success == key %>
<div class="alert alert-<%= key %>" style="margin:0px auto ;text-align: center;opacity: 0.2; ">
	تمت المعلومات بنجاح
<%end%>
<% if :notice == key %>
<div class="alert alert-<%= key %>" style="margin:0px auto ;text-align: center;opacity: 0.2; ">
لايسمح تخطي المنطقه يرجى الدخول
<%end%>
</div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
     
    </div>
  </body>
</html>

app/views/pages/index.html.erb
<center>
   <div class="holder_content1">
		<section>
  <%= link_to image_tag("one.png", :size => "700",:class=>"o") , services_path%>
	</section>
	

		</div>
		
   <div class="holder_content">
   
   <section class="group1">
   <h3>اسلوبنا</h3>
   	<p>بحول من الله وقوته نوفق ان نخدمكـم ونستبط الانزعاجات وتواليها بأفضل واسرع التقنيات واجودها ونضع لكم 
   		الفروق والحلول بعين بصيرتكم ونفيدكم من افكارنا ونناقشها معكم وما يطيب خاطركم واما عن مال قيمة جهودنا فهي متواضعه
   		  ولا تسبب لكم من ضيق في صدوركم والله الموفق </p>
    <a href=""></a>

	</section>
	

     
   <section class="group2">
   <h3>خدمــاتنـا</h3>
   	<p>تقسم اعمالنـا الحيوية في نظام الحاسب الى عدة انوية ظاهرية 
   <br />
   أولاها : خدمـاتنـا للتجارة مع الله عز وجل 
   <br />
        ثانيـها : خدمـاتنـا لأفراد المتجمع  
   <br />
      ثالهـا : خدمـاتنـا للفئات التجارية الصغيرة    
   <br />
   رابعـها : خدمـاتنـا للشركات والانظمة العلوية 
   
   		</p>
	<a href=""><span class="read_more"><%= link_to "اكمــ...ــل" , services_path%></span></a>

	</section>

       
   <section class="group3">
   <h3>من نحـن</h3>
   	<p>فـئة تخـدم المجتمـع بلصور المستدركة من الخبرات والعلوم العملية في الحاسب الالي من خدماتها وامثالها المتكررة من
   		ازالة عصبية الفايرس المسبب لعلول النظام والمتعدده الاحصائية ويغد عملنا بطريقتـه الحديثة التي فضلناها عن غيرنا </p>
	<a href=""><span class="read_more"><%= link_to "اكمــ...ــل" , aboutus_path%></span></a>

	</section>

   </div>

   <!--end holder-->
</center>
<br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />

app/views/pages/one1.html.erb
<center>
   <div class="holder_content1">
		<section>

	</section>
	

		</div>
		
   <div class="holder_content">
 
       <section class="group7">
   <h3>نشر المؤسسة بأعلى المواقع</h3>
   <br />
   	<p style="text-align: right;"class="microposts"> : في حين كثر انتشار المواقع كـ الفيسبوك والتويتر نقدم لكم هذه الخدمات المناسبة لكم </p>
   <table class="profile " summary="Profile information">
  <tr>
    <td class="main">
   
        <table class="microposts" summary="User microposts" style="text-align: center;width: 430px; color:#A9E7FF">
        	<tr >
        		<td >
       			نصف دينار
					</td>
        		<td>
        	عمل حساب  لكل  موقع منهم 
        			</td>
        		<td >
        			1
        			</td>
        		
        	</tr>
        	<tr>
        		 		<td >
       			 دينار ونصف
					</td>
        		<td>
        	عمل حسابات بإيميلات ساب-دومين للحماية  
        			</td>
        		<td >
        			2
        			</td>
        		
        	</tr>
        	
        		<tr>
        		 		<td >
       			 سبـعة دنانير
					</td>
        		<td>
عمل حساب بدومين جديد للمؤسسة
        			</td>
        		<td >
        			3
        			</td>
        		
        	</tr>
        		<tr>
        		 		<td >
        		 				إحدى عشر دينار
        		 								</td>
        		<td>
عمل جميع الحسابات المرغوبة مع دومين جديد
        			</td>
        		<td >
        			خدمة
        			</td>
        		
        	</tr>
        </table>
    </td>
    </tr>
    </table>
       	<p style="text-align: right;"class="o">وفي حالة الاستفسارات او رغبتـكم يمكنكـم التسجيل والمتابعه  </p>

	<a href=""class="o"><%= link_to "ســجل معنــا بدخولـــك" ,signin_path%></a>
	</section>  
   <section class="group6">
   	
   	  <%= image_tag("one1.png", :class=>"o")%>
  

	</section>

  
   </div>

   <!--end holder-->
</center>
<br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />

<br /><br /><br /><br /><br /><br /><br /><br />

app/views/pages/one2.html.erb
<center>
   <div class="holder_content1">
		<section>

	</section>
	

		</div>
		
   <div class="holder_content">
 
       <section class="group7">
   <h3>عمل موقع للمؤسسة</h3>
   <br />
   	<p class="microposts"> في حدود المؤسسات الدينية اكثرها تحتاج الى مواقع تشمل خطاهم واعمالهم الدينية وحركاتهم ومسيرتهم المتواصلة في الجهاد الاكبر
   		فإن وفقنا الله عز وجل نخدمكم بنشرها لكم على الانترنت سعياً لتطوير متجمعنـا النابض ويكون لنا ولكم صدقة جارية وهذه هي 
   		اختلافنـا وخدماتنـا لكم  </p>
   		   <h3>اختلافنا</h3>

   	<p style="text-align: right;" class="microposts">  اولاً:فضلنا استخدام الاليات الحديثة في البرمجه كـ الروبي بدلاً عن البي اتش بي</p>
   	
   	<p style="text-align: right;" class="microposts">  ثانيا:استخدمنا استضافة الهيروكو بدلاً عن الاستضافات الاخرى </p>
   	   <h3>خدمـاتنـا</h3>
   <table class="profile " summary="Profile information">
  <tr>
    <td class="main">
    
        <table class="microposts" summary="User microposts" style="text-align: center;width: 430px; color:#A9E7FF">
        	<tr >
        		<td >
       			إحدى عشر دينارا
					</td>
        		<td>
        	  تصمــيم واجـهة الموقع
        			</td>
        		<td >
        			1
        			</td>
        		
        	</tr>
        	<tr>
        		 		<td >
       			 دينار ونصف
					</td>
        		<td>
        			تصمــيم صفحه فرعية 
        			</td>
        		<td >
        			2
        			</td>
        		
        	</tr>
        	
        		<tr>
        		 		<td >
       			 خمسة دينار
					</td>
        		<td>
رفع الموقع على استضافة هيروكو وجت
        			</td>
        		<td >
        			3
        			</td>
        		
        	</tr>
        		<tr>
        		 		<td > 
        		 			سبعة دينار
        		 								</td>
        		<td>
شراء دومين وربطه بـ استصافة هيروكو
        			</td>
        		<td >
        			4
        			</td>
        		
        	</tr>
        	
        		<tr>
        		 		<td > 
        		 			 ثلاثة دينار
        		 								</td>
        		<td>
تركيـب انواع معينة من السكربتات الاسلامية
        			</td>
        		<td >
        			5
        			</td>
        		
        	</tr>
        	
        		<tr>
        		 		<td > 
        		 			تسعة عشر دينار
        		 								</td>
        		<td>
عمل موقع كامل ب5 صفحات مع دومين
        			</td>
        		<td >
        			خدمة
        			</td>
        		
        	</tr>
        	
        	
        </table>
    </td>
    </tr>
    </table>
           	<h3 style="text-align: right;">اجوبة الاسئلة الذهنية  </h3>
<br />
           	<p style="text-align: right;" class="microposts">اولاً:ان جميع مواقعنا تستخدم التقنيات التالية <span style="float: left;">[HTML5 SCSS JQUERY RAILS 3.2  ]</span> </p>

           	<p style="text-align: right;" class="microposts"> ثانيا: ان استضافة هيروكو من اقوى الاستضافات ولزيادة  المعلومات <span style="float: left;">Heroku.com</span></p>
   	<p style="text-align: right;" class="microposts"> ثالثا: ان البنية التحتيه للموقع مصممة بطريقة   <span style="float: left;">RubyOnRails3</span></p>
   	
<p style="text-align: right;" class="microposts"> رابعا: هذه الخدمات  للمؤسسات الدينية والمرتبطه بهـا   </p>
<p style="text-align: right;" class="microposts"> خامسا: السكربتات الاسلامية متوافرة في الانترنت بكثرة ويمكننا تطويرهم ان تطلب بشروط برمجيه وحقوقية  </p>
       	<br />
       	<p style="text-align: right;"class="o">وفي حالة الاستفسارات او رغبتـكم يمكنكـم التسجيل والمتابعه  </p>

	<a href="" class="e"><%= link_to "ســجل معنــا بدخولـــك" ,signin_path ,:class=>"o"%></a>
	</section>  
   <section class="group6">
   	
   	  <%= image_tag("one1.png", :class=>"o")%>
  

	</section>

  
   </div>

   <!--end holder-->
</center>
<br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />

<br /><br /><br /><br /><br /><br /><br /><br />
<br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />

<br /><br /><br /><br /><br /><br /><br /><br />

<br /><br /><br /><br /><br /><br /><br /><br />

app/views/pages/one3.html.erb
<center>
   <div class="holder_content1">
		<section>

	</section>
	

		</div>
		
   <div class="holder_content">
 
       <section class="group7">
   <h3>الصدقه الجارية للافراد</h3>
   <br />
   	<p class="microposts">
قال تعالى
( آَمِنُوا بِاللَّهِ وَرَسُولِهِ وَأَنْفِقُوا مِمَّا جَعَلَكُمْ مُسْتَخْلَفِينَ فِيهِ
فَالَّذِينَ آَمَنُوا مِنْكُمْ وَأَنْفَقُوا لَهُمْ أَجْرٌ كَبِيرٌ ) جعلنا الله واياكم من الذين ينفقون في مرضات الله الرب الرحيم ونشكره على توفيقنا
على تصميم هذا القسم والحمدلله عدد اختلاف الليل والنهار
 </p>
   		   <h3>انواع الصدقات</h3>

   	<p style="text-align: right;" class="microposts"> قال الامام البـاقر عليه السلام (زكاة العلم أن تعلمه عباد الله) وتكون الصدقة عن نشر علوم الرسول الاعظم ص واهل بيته 
   		واصحابة المنتجبين ارواحنا تحت مقدمهم كل الفداء</p>
    	   <h3>الصدقات الجارية</h3>
   <table class="profile " summary="Profile information">
  <tr>
    <td class="main">
    
        <table class="microposts" summary="User microposts" style="text-align: center;width: 430px; color:#A9E7FF">
        	<tr >
        		<td >
       			دينار
					</td>
        		<td>
        	  تركيب سكربت للفرد
        			</td>
        		<td >
        			1
        			</td>
        		
        	</tr>
        	<tr>
        		 		<td >
       			 مجانا   
					</td>
        		<td>
        			تركيب سكربت الصدقه الجارية قريبا  
        			</td>
        		<td >
        			خدمة
        			</td>
        		
        	</tr>
        	
        		<tr>
        		 		<td >
       			 ثلاثة دينار
					</td>
					
        		<td>
 عمل موقع شامل ل5 سكربتات مطلوبة
        			</td>
        		<td >
        			خدمة
        			</td>
        		
        	</tr>
        		<tr>
        		 		<td > 
        		 			خمسة عشر دينار
        		 								</td>
        		<td>
تحديد متطلبات الفرد للصدقه مع الاستضافة بدومين
        			</td>
        		<td >
        			خدمة
        			</td>
        		
        	</tr>
        	
        	
        </table>
    </td>
    </tr>
    </table>
           	<h3 style="text-align: right;">اجوبة الاسئلة الذهنية  </h3>
<br />
           	<p style="text-align: right;" class="microposts">اولاً:ان جميع مواقعنا تستخدم التقنيات التالية <span style="float: left;">[HTML5 SCSS JQUERY RAILS 3.2 ]</span> </p>

           	<p style="text-align: right;" class="microposts"> ثانيا: ان استضافة هيروكو من اقوى الاستضافات ولزيادة  المعلومات <span style="float: left;">Heroku.com</span></p>
   	<p style="text-align: right;" class="microposts"> ثالثا: ان البنية التحتيه للموقع مصممة بطريقة   <span style="float: left;">RubyOnRails3</span></p>
   	
<p style="text-align: right;" class="microposts"> رابعا : ان سكربت الصدقه الجارية يتم بإذن الله تعالى في تاريخ 1-5-2012   </p>
<p style="text-align: right;" class="microposts"> خامسا: السكربتات الاسلامية متوافرة في الانترنت بكثرة   </p>
       	<br />
       	<p style="text-align: right;"class="o">وفي حالة الاستفسارات او رغبتـكم يمكنكـم التسجيل والمتابعه  </p>

	<a href="" class="e"><%= link_to "ســجل معنــا بدخولـــك" ,signin_path ,:class=>"o"%></a>
	</section>  
   <section class="group6">
   	
   	  <%= image_tag("one1.png", :class=>"o")%>
  

	</section>

  
   </div>

   <!--end holder-->
</center>
<br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />

<br /><br /><br /><br /><br /><br /><br /><br />
<br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />

<br /><br /><br /><br /><br /><br /><br /><br />

app/views/pages/send_email.html.erb
<h1>MyApp's contact form</h1>

<p>Name: <%= @user_info["name"] %></p>
<p>Email: <%= @user_info["email"] %></p>
<p>Message: <%= @user_info["message"] %></p>

app/views/pages/services.html.erb
<center>
   <div class="holder_content1">
		<section>
  <%= image_tag("two.png", :size => "700",:class=>"c")%>
	</section>
		</div>
		
   <div class="holder_content">
   
   <section class="group1">
   <h3>للفـئات التجارية </h3>
   
      	<p>   <%= link_to "اولها : التدوير على اجهزتهم بفترات " ,services_7_path%>
      		      	<p>   <%= link_to "ثانيها :عمل مواقع تخدمهـم " ,services_8_path%>
      		      	<p>   <%= link_to "ثـالثها :عمل شبكات لاسلكية  " ,services_9_path%>

      	<p>   رابعها : عمل اجهزة سيرفر ؟قريبا؟
   </p>
	</section>
	

     
   <section class="group2">
   <h3>لأفراد المجتمع </h3>
   
      	<p>   <%= link_to "اولها :وضع السيرة الذاتيه في موقع " ,services_5_path%>
   
      	<p>   <%= link_to "ثانيها : اصلاح حواسيبهم في منزلهم " ,services_6_path%>
   
      	<p>   <%= link_to "ثـالثها : عروض آخر الاجهزة " ,sounds_path%>
   
      	<p>   رابعها : عمل البحوث والمشاريع ؟قريبا؟
	</section>

       
   <section class="group3">
   <h3> الربح مع الله تعالى</h3>
      	<p>   <%= link_to "اولها :نشر المؤسسة بأعلى المواقع" ,services_1_path%>

      	<p>   <%= link_to "ثانيها : عمل موقع للمؤسسة" ,services_2_path%>

      	<p>   <%= link_to "ثـالثها : الصدقه الجارية للافراد" ,services_3_path%>

      	<p>   <%= link_to "رابعها : أسعـار خاصة على  اصلاح الاجهزة" ,services_4_path%>


	</section>

   </div>

   <!--end holder-->
</center>
<br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />